"""
Pharmacist Assistant Router
Approved users type a drug name and receive general, structured drug information
in Arabic (name, side effects, usage times), generated by Gemini (same key /
failover as the rest of the app). Each lookup is saved to the user's query
history (the ``user_queries`` table).
"""

from fastapi import APIRouter, Depends, HTTPException, status, Query
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, desc

from app.database import get_db
from app.models.user import User
from app.models.user_query import UserQuery
from app.schemas.assistant import (
    DrugInfoRequest,
    DrugInfoResponse,
    DrugQueryHistoryItem,
)
from app.services.auth_service import get_current_approved_user
from app.services import assistant_service

router = APIRouter(prefix="/assistant", tags=["Assistant"])


@router.post("/drug-info", response_model=DrugInfoResponse)
async def drug_info(
    request: DrugInfoRequest,
    user: User = Depends(get_current_approved_user),
    db: AsyncSession = Depends(get_db),
):
    """
    Return general drug information (name, side effects, usage times) for the
    requested drug name, and record the lookup in the user's query history.
    """
    name = request.name.strip()
    if not name:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Drug name is required.",
        )

    result = await assistant_service.get_drug_info(name, user, db)

    # Persist the lookup in the user's query history. Never let a history write
    # failure break the user-facing response.
    try:
        db.add(UserQuery(
            user_id=user.id,
            query_text=name[:120],
            recognized=bool(result.get("recognized")),
            result={
                "name": result.get("name", ""),
                "activeIngredient": result.get("activeIngredient", ""),
                "uses": result.get("uses", []),
                "dosage": result.get("dosage", []),
                "sideEffects": result.get("sideEffects", []),
                "warnings": result.get("warnings", []),
                "contraindications": result.get("contraindications", []),
                "usageTimes": result.get("usageTimes", []),
            },
        ))
        await db.flush()
    except Exception as e:  # noqa: BLE001
        print(f"[Assistant Router] Failed to save query history: {e}")

    return DrugInfoResponse(**result)


@router.get("/history", response_model=list[DrugQueryHistoryItem])
async def query_history(
    limit: int = Query(20, ge=1, le=100),
    user: User = Depends(get_current_approved_user),
    db: AsyncSession = Depends(get_db),
):
    """Return the current user's most recent drug-assistant lookups."""
    result = await db.execute(
        select(UserQuery)
        .where(UserQuery.user_id == user.id)
        .order_by(desc(UserQuery.created_at))
        .limit(limit)
    )
    return result.scalars().all()
